version: '3.8'

networks:
  mynetwork:  # Define a custom network
    driver: bridge

services:
  depends_on: localstack
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - LOCALSTACK_HOST=localstack  # Use the service name as hostname
    networks:
      - default
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - default
    volumes:
      - ./frontend:/app

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DATA_DIR=/var/lib/localstack
    networks:
      - default
    volumes:
      - "./localstack_data:/var/lib/localstack"
